"""
Handler for 'Create' actions.
Ensures missing asset records are initialized in assets.json.
"""
from ..asset_manager import create_asset

def handle_create(action, all_assets):
    """
    Creates a new asset record for a missing chapter piece.
    """
    atype = action.get("asset_type")
    book_id = action.get("book_id")
    chapter_id = action.get("chapter_id")
    
    # We create the asset with default 'not_started' status
    # Except 'chapter' which is usually 'done' if the chunk exists 
    # (actually chunk existence IS our trigger)
    prod_status = "not_started"
    if atype == "chapter":
        prod_status = "publish" # Final state since chunk exists
        
    asset = create_asset({
        "id": f"asset_{atype}_{chapter_id}",
        "type": atype,
        "title": f"Autogenerated {atype.replace('_', ' ')}",
        "book_id": book_id,
        "chapter_id": chapter_id,
        "production": prod_status
    })
    
    return {"success": True, "asset_id": asset["id"]}
